package util

const val MENU_SALES = 1
const val MENU_EMPLOYEE = 2
const val MENU_ORDERS = 3
const val MENU_EXIT = 4

const val CATEGORY_PRODUCT_APPLIANCES = 1
const val CATEGORY_PRODUCT_BEDROOM = 2
const val CATEGORY_PRODUCT_WATERANDDRINKS = 3
const val CATEGORY_PRODUCT_TECHNOLOGIES = 4
const val CATEGORY_PRODUCT_BAKERYANDPASTRY = 5
const val CATEGORY_PRODUCT_GROCERY = 6